# Sobre los autores {#author .unnumbered}

Yihui es el desarrollador principal del paquete **blogdown**. No comenzó a trabajar en la documentación sistemática (es decir, este libro) hasta cuatro meses después de comenzar el proyecto **blogdown**. Un día, encontró un tutorial de **blogdown** muy agradable en Twitter escrito por Amber Thomas. Sorprendido de que pudiera crear un gran sitio web personal usando **blogdown** y escribir un tutorial _cuando no había documentación oficial_, Yihui inmediatamente la invitó a unirse a él para escribir este libro, aunque nunca antes se habían conocido. Esto definitivamente no habría sucedido si Amber no tuviera un sitio web. Por cierto, Amber formuló [la primera pregunta](https://stackoverflow.com/q/41176194/559676) con la etiqueta `blogdown` en StackOverflow.

Alrededor de medio año después, Yihui vio otro tutorial de **blogdown** muy bien escrito por Alison en su sitio web personal, cuando este libro todavía no estaba completo. Sucedió lo mismo, y Alison se convirtió en el tercer autor de este libro. Los tres autores no se conocían.

Con suerte, puede ver mejor por qué debería tener un sitio web ahora.

## Yihui Xie {-}

Yihui Xie (<https://yihui.name>) es ingeniero de software en RStudio (<https://www.rstudio.com>). Obtuvo su doctorado en el Departamento de Estadística de la Universidad Estatal de Iowa. Está interesado en gráficos estadísticos interactivos y computación estadística. Como usuario de R activo, es autor de varios paquetes en R, como **knitr**, **bookdown**, **blogdown**, **xaringan**, **animation**, **DT**, **tufte**, **formatR**, **fun**, **mime**, **highr**, **servr**, y **Rd2roxygen**, entre los cuales **animation** ganó el premio John M. Chambers Statistical Software Award (ASA) 2009 . También fue coautor de algunos otros paquetes R, entre los que se incluyen **shiny**, **rmarkdown** y **leaflet**.

En 2006, fundó Capital of Statistics (<https://cosx.org>), que se ha convertido en una gran comunidad en línea de estadísticas en China. Inició la conferencia de R de China en 2008 y desde entonces ha participado en la organización de conferencias de R en China. Durante su formación de doctorado en la Iowa State University, ganó el Vince Sposito Statistical Computing Award (2011) y el Snedecor Award (2012) en el Departamento de Estadística.

De vez en cuando despotrica en Twitter (https://twitter.com/xieyihui), y la mayoría de las veces lo pueden encontrar en GitHub (https://github.com/yihui).

Le gusta la comida picante tanto como la literatura china clásica.

## Amber Thomas {-}

Amber Thomas (<https://amber.rbind.io>) es periodista de datos y "creadora" de la publicación en línea de ensayos visuales: The Pudding (<https://pudding.cool>). Sin embargo, su formación académica se encontraba en un campo completamente diferente: la biología marina. Tiene una licenciatura en biología marina y química de la Universidad Roger Williams y una maestría en ciencias marinas de la Universidad de Nueva Inglaterra. A lo largo de su carrera académica y profesional como bióloga marina, se dio cuenta de que amaba el análisis de datos, la visualización y la narración de historias a través de los datos y, por lo tanto, cambió las trayectorias profesionales por algo un poco más centrado en los datos.

Mientras buscaba trabajo, comenzó a realizar proyectos personales para ampliar su conocimiento del funcionamiento interno de R. Decidió poner todos sus proyectos en un solo lugar en línea (para que pudiera ser descubierta, naturalmente) y después de muchas búsquedas, tropezó con un lanzamiento anticipado del paquete **blogdown**. Se enganchó de inmediato y pasó unos días configurando su sitio web personal y escribiendo un tutorial sobre cómo lo hizo. Puede encontrar ese tutorial y algunos de sus otros proyectos y reflexiones en su sitio de blogdown.

Cuando no está machacando números y tratando de mantenerse al tanto de la bandeja de entrada de su correo electrónico, por lo general, Amber recibe aire fresco de Seattle o se acurruca con su perro, Sherlock. Si la está buscando en el mundo digital, pruebe <https://twitter.com/ProQuesAsker>.


## Alison Presmanes Hill {-}

Alison (<https://alison.rbind.io>) es profesora de pediatría en el Centro para el Entendimiento del Lenguaje Hablado de la Universidad de Salud y Ciencia de Oregon (OHSU, por sus siglas en inglés) en Portland, Oregon. Alison obtuvo su doctorado en psicología del desarrollo con una concentración en métodos cuantitativos de la Universidad de Vanderbilt en 2008. Su investigación actual se centra en desarrollar mejores medidas de resultado para evaluar el impacto de nuevos tratamientos para niños con autismo y otros trastornos del neurodesarrollo, utilizando procesamiento del lenguaje natural y otros métodos computacionales. Alison es autora de numerosos artículos de revistas y capítulos de libros, y su trabajo ha sido financiado por los Institutos Nacionales de Salud, el Instituto de Investigación Translacional y Clínica de Oregón y Autism Speaks.

Además de la investigación, Alison imparte cursos de postgrado en el programa de Ciencias de la Computación de OHSU (https://www.ohsu.edu/csee) sobre estadística, ciencia de datos y visualización de datos usando R. También ha desarrollado y dirigido varios talleres de R y sesiones de entrenamiento en equipos más pequeñas, y le encanta entrenar nuevos "usuarios". Puede encontrar algunos de sus talleres y materiales de enseñanza en GitHub (https://github.com/apreshill) y, por supuesto, en su sitio **blogdown**.

Siendo una madre nueva, los libros favoritos actuales de Alison son *The Circus Ship* y *Bats at the Ballgame*. También realiza interpretaciones entusiastas de la mayoría de las canciones de Emily Arrow (solo para audiencias privadas).