# Experiencia personal

Empecé a bloguear en blogchina.com en 2005, me mudé a blog.com.cn, luego a MSN Space, y finalmente compré mi propio dominio `yihui.name` y un host virtual. Primero usé una aplicación PHP llamada Bo-Blog, luego cambié a WordPress, y luego a Jekyll. Finalmente me mudé a Hugo. Aunque me he mudado varias veces, todas mis publicaciones se han conservado, y todavía se puede ver mi primera publicación en chino en 2005. A menudo hago mi mejor esfuerzo para no introducir enlaces rotos (que conducen a la página 404) cada vez que cambio la publicación backend de mi sitio web. Cuando sea demasiado difícil preservar los enlaces originales de ciertas páginas, redirigiré las URL rotas a las nuevas URL. Es por eso que es importante que su sistema admita redirecciones, y en particular, 301 redirecciones (Netlify hace un buen trabajo aquí). Estas son algunas de mis reglas de redireccionamiento: https://github.com/rbind/yihui/blob/master/static/_redirects. Por ejemplo, `http://yihui.name/en/feed/` era la fuente RSS de mis viejos blogs de WordPress y Jekyll en inglés, y Hugo genera la fuente RSS a `/en/index.xml` en su lugar, así que necesita redirigir `/en/feed/` a `/en/index.xml`.

Google ha proporcionado varias herramientas para ayudarlo a obtener más información sobre su sitio web. Por ejemplo, [Google Analytics](https://analytics.google.com) puede recopilar estadísticas de visitantes y dar sugerencias de velocidad para su sitio web. [Google Webmasters](https://www.google.com/webmasters/) puede mostrarle los enlaces rotos que encuentra. Uso estas herramientas con frecuencia.

Creo firmemente en el valor de escribir. Con los años, he escrito más de 1000 publicaciones en chino e inglés. Algunos son largos, y la mayoría son cortos. El tamaño total de estos archivos de texto es de aproximadamente 5 Mb. En retrospectiva, la mayoría de los mensajes probablemente no son valiosos para los lectores en general (algunos son pensamientos aleatorios, y algunos son mis discursos), pero creo que me beneficié mucho de escribir en dos aspectos:

1. Si me siento y me concentro en escribir un tema pequeño por un tiempo, a menudo siento que mis pensamientos serán más claros. Una gran diferencia entre escribir y hablar es que siempre puedes reorganizar las cosas y revisarlas al escribir. No creo que escribir en redes sociales cuente. 140 caracteres bien pueden ser reflexivos, pero siento que hay mucho caos allí. Es difícil plantear pensamientos sistemáticos solo a través de mensajes cortos, y estos mensajes rápidos a menudo se olvidan rápidamente.

1. Sé que algunos bloggers están en contra de los comentarios, por lo que no abren comentarios al público. Todavía no he tenido una experiencia muy negativa con los comentarios. Por el contrario, constantemente encuentro inspiraciones de los comentarios. Por ejemplo, [Estaba pensando](https://yihui.name/en/2013/04/travis-ci-for-r/) si era posible verificar automáticamente los paquetes en R en la nube a través de Travis CI. En ese momento (abril de 2013), creo que no mucha gente en la comunidad R había comenzado a usar Travis CI, aunque no estoy seguro si fui la primera persona que experimentó con esta idea. Sentí que Travis CI podría ser prometedor, pero no fue compatible con R en ese momento. Alguien llamado Vincent Arel-Bundock (todavía no lo conozco) me contó un truco en un comentario, que de repente me iluminó y rápidamente descubrí una solución. En octubre de 2013, Craig Citro comenzó un trabajo más sólido en el apoyo de R en Travis CI. No sé si vio mi publicación en el blog. De todos modos, creo que Travis CI ha tenido un impacto sustancial en los desarrolladores de paquetes en R, que es algo grandioso para la comunidad de R.

Otro beneficio relativamente pequeño es que a menudo voy a mis propios posts para aprender algunas cosas técnicas que he olvidado. Por ejemplo, me resulta difícil recordar la sintaxis de diferentes tipos de aserciones de ancho cero en expresiones regulares similares a Perl: `(?=...)`, `(?!...)`, `(?<=...)`, y` (?<!...)`. Así que escribí una breve publicación en el blog y me di algunos ejemplos mínimos. Después de volver a esa publicación varias veces, finalmente puedo recordar cómo usar estas expresiones regulares.